# standalone mode
listen=YES
listen_ipv6=NO
background=NO

# allow local users and allow write
local_enable=YES
write_enable=YES
chmod_enable=YES
local_umask=002
dirmessage_enable=YES
use_localtime=YES

# logging
xferlog_enable=YES
connect_from_port_20=YES
xferlog_std_format=YES

# security/chroot
chroot_local_user=YES
allow_writeable_chroot=YES
seccomp_sandbox=NO

# passive mode
pasv_enable=YES
pasv_min_port=21100
pasv_max_port=21110
pasv_address=127.0.0.1

# user rules
userlist_enable=YES
userlist_file=/etc/vsftpd/vsftpd.userlist
userlist_deny=NO
